####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Dnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/medsync-backend .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/medsync-backend
#
# The ` registry.access.redhat.com/ubi9/ubi-minimal:9.7` base image is based on UBI 9.
# To use UBI 8, switch to `quay.io/ubi8/ubi-minimal:8.10`.
###
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7
WORKDIR /work/
RUN echo "quarkus:x:1001:1001:quarkus user:/work:/sbin/nologin" >> /etc/passwd \
    && echo "quarkus:x:1001:" >> /etc/group \
    && chown quarkus /work \
    && chmod "g+rX" /work \
    && chown quarkus:root /work
COPY --chown=quarkus:root --chmod=0755 target/*-runner /work/application

EXPOSE 8080
USER quarkus

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
